/* eslint-disable prettier/prettier */
export enum TipoNotificacion {
    CONFIRMACION_RESERVA = 'CONFIRMACION_RESERVA',
    RECHAZO_RESERVA = 'RECHAZO_RESERVA',
    CANCELACION_RESERVA = 'CANCELACION_RESERVA',
    ALERTA_PROMOCION = 'ALERTA_PROMOCION'
}